name: Continious Integration and Contitnious Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run
      run: echo $VARRRR

    - name: PWD
      run: pwd

    - name: ls
      run: ls

    - run: echo ${{secrets.DOCKER_HUB_USERNAME}} 
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tonujet/iit-lab4:$(date +%s)
    
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWD}}       
