name: Continious Integration and Contitnious Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  linter:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Install html linter
        run: pip install djlint

      - name: Lint all html code
        run: djlint . --reformat


  build:
    needs: linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tonujet/iit-lab4
    
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Push image to docker hub
      run: docker push tonujet/iit-lab4

    - name: List all docker images
      run: docker image ls

    - name: Clear all docker images
      run: docker rmi -f $(docker images -aq)


  provision:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
        
    env:
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}

    steps:
      - uses: actions/checkout@v4
      
      - uses: terraform-compliance/github_action@0.3.0
        with:
          quit-early: true 
      
      - name: Init terraform
        run: terraform init

      - name: Apply terraform
        run: terraform apply -auto-approve

      
          
      


    
